//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfoy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string EducationName { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
